version: '3.7'

volumes:
    grafana: 
    prometheus_data:

services:
    otel-collector:
        image: otel/opentelemetry-collector-contrib:latest
        hostname: otel-collector
        command: ["--config=/etc/otel-collector-config.yaml"]
        volumes:
          - ./otel-collector/config.yaml:/etc/otel-collector-config.yaml
        ports:
          # - "8888:8888" # Prometheus metrics exposed by the collector for scrape 
          - "8889:8889" # Prometheus exporter metrics
          - "13133:13133" # health_check extension
          - "4317:4317" # OTLP gRPC receiver
          - "4318:4318" # OTLP http receiver
          # - 55679:55679 # zpages extension
    prometheus:
        image: prom/prometheus:latest
        hostname: prometheus
        volumes:
          - ./prometheus/:/etc/prometheus/
          - prometheus_data:/prometheus
        command:
          - '--config.file=/etc/prometheus/prometheus.yml'
          - '--storage.tsdb.path=/prometheus'
          # - '--enable-feature=otlp-write-receiver'
        ports:
          - 9090:9090
    grafana:
        image: grafana/grafana-oss:latest-ubuntu
        hostname: grafana
        ports: 
            - "3000:3000" #UI
        volumes:
            - grafana:/var/lib/grafana
            - ./grafana/provisioning:/etc/grafana/provisioning
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
            - GF_AUTH_DISABLE_LOGIN_FORM=true
        depends_on:
            - prometheus