version: '3.7'

volumes:
    grafana:
    prometheus_data:

services:
    prometheus:
        image: prom/prometheus:latest
        hostname: prometheus
        volumes:
          - ./prometheus/:/etc/prometheus/
          - prometheus_data:/prometheus
        command:
          - '--config.file=/etc/prometheus/prometheus.yml'
          - '--storage.tsdb.path=/prometheus'
        ports:
          - 9090:9090
    grafana:
        image: grafana/grafana-oss:latest-ubuntu
        hostname: grafana
        ports: 
            - "3000:3000" #UI
        volumes:
            - grafana:/var/lib/grafana
            - ./grafana/provisioning:/etc/grafana/provisioning
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
            - GF_AUTH_DISABLE_LOGIN_FORM=true
        depends_on:
            - prometheus